[package]
name = "imgshow"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.22"
image = "0.23.14"
eframe = "0.14.0" # Gives us egui, epi and web+native backends